export const menuProjectSeed = {
  data: {
    name: '核心数据管理',
    icon: 'i-ant-design:apartment-outlined',
    sort: 2,
    type: 'C',
    path: '/project',
    createBy: 'admin',
    children: {
      create: [
        {
          name: '最终用户',
          icon: 'i-ant-design:cluster-outlined',
          sort: 1,
          path: '/project/factory',
          type: 'M',
          createBy: 'admin',
          children: {
            create: [
              {
                name: '最终用户工作台',
                icon: 'i-ant-design:cluster-outlined',
                sort: 1,
                path: '/project/factory/:id',
                type: 'M',
                hidden: true,
                createBy: 'admin',
                permission: 'project:factory:workTable',
              },
              {
                name: '创建',
                path: '',
                type: 'B',
                createBy: 'admin',
                permission: 'project:factory:create',
              },
              {
                name: '查询',
                path: '',
                type: 'B',
                createBy: 'admin',
                permission: 'project:factory:query',
              },
              {
                name: '修改',
                path: '',
                type: 'B',
                createBy: 'admin',
                permission: 'project:factory:update',
              },
              {
                name: '删除',
                path: '',
                type: 'B',
                createBy: 'admin',
                permission: 'project:factory:delete',
              },
            ],
          },
        },
        {
          name: '装置管理',
          icon: 'i-ant-design:deployment-unit-outlined',
          sort: 2,
          type: 'M',
          path: '/project/device',
          createBy: 'admin',
          hidden: true,
          children: {
            create: [
              {
                name: '创建',
                path: '',
                type: 'B',
                createBy: 'admin',
                permission: 'project:device:create',
              },
              {
                name: '查询',
                path: '',
                type: 'B',
                createBy: 'admin',
                permission: 'project:device:query',
              },
              {
                name: '修改',
                path: '',
                type: 'B',
                createBy: 'admin',
                permission: 'project:device:update',
              },
              {
                name: '删除',
                path: '',
                type: 'B',
                createBy: 'admin',
                permission: 'project:device:delete',
              },
            ],
          },
        },
        {
          name: '装置列表',
          icon: 'i-ant-design:deployment-unit-outlined',
          sort: 3,
          hidden: true,
          type: 'M',
          path: '/project/device/:id',
          createBy: 'admin',
          children: {
            create: [
              {
                name: '创建',
                path: '',
                type: 'B',
                createBy: 'admin',
                permission: 'project:device:create',
              },
              {
                name: '查询',
                path: '',
                type: 'B',
                createBy: 'admin',
                permission: 'project:device:query',
              },
              {
                name: '修改',
                path: '',
                type: 'B',
                createBy: 'admin',
                permission: 'project:device:update',
              },
              {
                name: '删除',
                path: '',
                type: 'B',
                createBy: 'admin',
                permission: 'project:device:delete',
              },
            ],
          },
        },
        {
          name: '阀门管理',
          icon: 'i-ant-design:dashboard-outlined',
          sort: 4,
          type: 'M',
          path: '/project/valve',
          createBy: 'admin',
          children: {
            create: [
              {
                name: '历史数据',
                icon: 'i-ant-design:dashboard-outlined',
                sort: 1,
                type: 'M',
                hidden: true,
                path: '/project/valve/historyData/:id',
                permission: 'project:valve:historyData',
                createBy: 'admin',
              },
              {
                name: '历史评分',
                icon: 'i-ant-design:dashboard-outlined',
                sort: 1,
                type: 'M',
                hidden: true,
                path: '/project/valve/history/:id',
                permission: 'project:valve:history',
                createBy: 'admin',
              },
              {
                name: '工单列表',
                icon: 'i-ant-design:dashboard-outlined',
                sort: 1,
                type: 'M',
                path: '/project/valve/workOrder/:id',
                permission: 'project:valve:workOrder',
                hidden: true,
                createBy: 'admin',
              },
              {
                name: '阀门列表',
                icon: 'i-ant-design:dashboard-outlined',
                sort: 1,
                type: 'M',
                path: '/project/valve/:id',
                permission: 'project:valve:list',
                hidden: true,
                createBy: 'admin',
              },
              {
                name: '阀门详情编辑',
                icon: 'i-ant-design:dashboard-outlined',
                sort: 1,
                type: 'M',
                path: '/project/valve/detail/:id',
                permission: 'project:valve:update',
                hidden: true,
                createBy: 'admin',
              },
              {
                name: '阀门评分',
                icon: 'i-ant-design:dashboard-outlined',
                sort: 1,
                type: 'M',
                path: '/project/valve/score/:id',
                permission: 'project:valve:score',
                hidden: true,
                createBy: 'admin',
              },
              {
                name: '阀门运行数据',
                icon: 'i-ant-design:dashboard-outlined',
                sort: 1,
                type: 'M',
                path: '/project/valve/runInfo/:id',
                permission: 'project:valve:runInfo',
                hidden: true,
                createBy: 'admin',
              },
              {
                name: '创建',
                path: '',
                type: 'B',
                createBy: 'admin',
                permission: 'project:valve:create',
              },
              {
                name: '查询',
                path: '',
                type: 'B',
                createBy: 'admin',
                permission: 'project:valve:query',
              },
              {
                name: '修改',
                path: '',
                type: 'B',
                createBy: 'admin',
                permission: 'project:valve:update',
              },
              {
                name: '删除',
                path: '',
                type: 'B',
                createBy: 'admin',
                permission: 'project:valve:delete',
              },
            ],
          },
        },
        {
          name: '项目管理',
          icon: 'i-ant-design:cloud-server-outlined',
          sort: 6,
          path: '/project/contract',
          createBy: 'admin',
          hidden: true,
          type: 'M',
          children: {
            create: [
              {
                name: '创建',
                path: '',
                type: 'B',
                createBy: 'admin',
                permission: 'project:contract:create',
              },
              {
                name: '查询',
                path: '',
                type: 'B',
                createBy: 'admin',
                permission: 'project:contract:query',
              },
              {
                name: '修改',
                path: '',
                type: 'B',
                createBy: 'admin',
                permission: 'project:contract:update',
              },
              {
                name: '删除',
                path: '',
                type: 'B',
                createBy: 'admin',
                permission: 'project:contract:delete',
              },
            ],
          },
        },
        {
          name: '项目列表',
          icon: 'i-ant-design:cloud-server-outlined',
          sort: 7,
          hidden: true,
          type: 'M',
          path: '/project/contract/:id',
          createBy: 'admin',
          children: {
            create: [
              {
                name: '创建',
                path: '',
                type: 'B',
                createBy: 'admin',
                permission: 'project:contract:create',
              },
              {
                name: '查询',
                path: '',
                type: 'B',
                createBy: 'admin',
                permission: 'project:contract:query',
              },
              {
                name: '修改',
                path: '',
                type: 'B',
                createBy: 'admin',
                permission: 'project:contract:update',
              },
              {
                name: '删除',
                path: '',
                type: 'B',
                createBy: 'admin',
                permission: 'project:contract:delete',
              },
            ],
          },
        },
        {
          name: '分析任务',
          icon: 'i-ant-design:line-chart-outlined',
          sort: 8,
          path: '/project/analysisTask',
          type: 'M',
          createBy: 'admin',
          children: {
            create: [
              {
                name: '创建',
                path: '',
                type: 'B',
                createBy: 'admin',
                permission: 'project:analysisTask:create',
              },
              {
                name: '查询',
                path: '',
                type: 'B',
                createBy: 'admin',
                permission: 'project:analysisTask:query',
              },
              {
                name: '修改',
                path: '',
                type: 'B',
                createBy: 'admin',
                permission: 'project:analysisTask:update',
              },
              {
                name: '删除',
                path: '',
                type: 'B',
                createBy: 'admin',
                permission: 'project:analysisTask:delete',
              },
              {
                name: '执行',
                path: '',
                type: 'B',
                createBy: 'admin',
                permission: 'project:analysisTask:execute',
              },
            ],
          },
        },
        {
          name: '任务列表',
          icon: 'i-ant-design:line-chart-outlined',
          sort: 9,
          path: '/project/analysisTask/:id',
          type: 'M',
          hidden: true,
          createBy: 'admin',
          children: {
            create: [
              {
                name: '创建',
                path: '',
                type: 'B',
                createBy: 'admin',
                permission: 'project:analysisTask:create',
              },
              {
                name: '查询',
                path: '',
                type: 'B',
                createBy: 'admin',
                permission: 'project:analysisTask:query',
              },
              {
                name: '修改',
                path: '',
                type: 'B',
                createBy: 'admin',
                permission: 'project:analysisTask:update',
              },
              {
                name: '删除',
                path: '',
                type: 'B',
                createBy: 'admin',
                permission: 'project:analysisTask:delete',
              },
            ],
          },
        },
      ],
    },
  },
};
