export const ddd = [
  {
    id: 151,
    name: '行程',
    value: 'Travel',
    sort: 1,
    status: true,
    createBy: 'admin',
    updateBy: null,
    createdAt: '2024-08-02 15:36:07',
    updatedAt: '2024-08-02 15:36:07',
    remark: '',
    dictTypeId: 6,
    treeId: 6,
    tree: {
      id: 6,
      name: '状态监视器',
      value: 'Status Monitor',
      remark: null,
      parentId: 1,
    },
  },
  {
    id: 153,
    name: '供气压力',
    value: 'Supply Pressure',
    sort: 1,
    status: true,
    createBy: 'admin',
    updateBy: null,
    createdAt: '2024-08-02 15:36:07',
    updatedAt: '2024-08-02 15:36:07',
    remark: '',
    dictTypeId: 6,
    treeId: 6,
    tree: {
      id: 6,
      name: '状态监视器',
      value: 'Status Monitor',
      remark: null,
      parentId: 1,
    },
  },
  {
    id: 155,
    name: '仪表模式',
    value: 'Instrument Mode',
    sort: 1,
    status: true,
    createBy: 'admin',
    updateBy: null,
    createdAt: '2024-08-02 15:36:07',
    updatedAt: '2024-08-02 15:36:07',
    remark: '',
    dictTypeId: 6,
    treeId: 6,
    tree: {
      id: 6,
      name: '状态监视器',
      value: 'Status Monitor',
      remark: null,
      parentId: 1,
    },
  },
  {
    id: 156,
    name: '行程累计器',
    value: 'Travel Accumulator',
    sort: 1,
    status: true,
    createBy: 'admin',
    updateBy: null,
    createdAt: '2024-08-02 15:36:07',
    updatedAt: '2024-08-02 15:36:07',
    remark: '',
    dictTypeId: 6,
    treeId: 6,
    tree: {
      id: 6,
      name: '状态监视器',
      value: 'Status Monitor',
      remark: null,
      parentId: 1,
    },
  },
  {
    id: 157,
    name: '放大器调整',
    value: 'Relay Adjustment',
    sort: 1,
    status: true,
    createBy: 'admin',
    updateBy: null,
    createdAt: '2024-08-02 15:36:07',
    updatedAt: '2024-08-02 15:36:07',
    remark: '',
    dictTypeId: 6,
    treeId: 6,
    tree: {
      id: 6,
      name: '状态监视器',
      value: 'Status Monitor',
      remark: null,
      parentId: 1,
    },
  },
  {
    id: 158,
    name: '最高温度记录',
    value: 'Max Recorded Temp',
    sort: 1,
    status: true,
    createBy: 'admin',
    updateBy: null,
    createdAt: '2024-08-02 15:36:07',
    updatedAt: '2024-08-02 15:36:07',
    remark: '',
    dictTypeId: 6,
    treeId: 6,
    tree: {
      id: 6,
      name: '状态监视器',
      value: 'Status Monitor',
      remark: null,
      parentId: 1,
    },
  },
  {
    id: 159,
    name: '运行时间',
    value: 'Run Time',
    sort: 1,
    status: true,
    createBy: 'admin',
    updateBy: null,
    createdAt: '2024-08-02 15:36:07',
    updatedAt: '2024-08-02 15:36:07',
    remark: '',
    dictTypeId: 6,
    treeId: 6,
    tree: {
      id: 6,
      name: '状态监视器',
      value: 'Status Monitor',
      remark: null,
      parentId: 1,
    },
  },
  {
    id: 160,
    name: '启动次数',
    value: 'Number of Powerups',
    sort: 1,
    status: true,
    createBy: 'admin',
    updateBy: null,
    createdAt: '2024-08-02 15:36:07',
    updatedAt: '2024-08-02 15:36:07',
    remark: '',
    dictTypeId: 6,
    treeId: 6,
    tree: {
      id: 6,
      name: '状态监视器',
      value: 'Status Monitor',
      remark: null,
      parentId: 1,
    },
  },
  {
    id: 161,
    name: '仪表等级',
    value: 'Instrument Level',
    sort: 1,
    status: true,
    createBy: 'admin',
    updateBy: null,
    createdAt: '2024-08-02 15:36:07',
    updatedAt: '2024-08-02 15:36:07',
    remark: '',
    dictTypeId: 6,
    treeId: 6,
    tree: {
      id: 6,
      name: '状态监视器',
      value: 'Status Monitor',
      remark: null,
      parentId: 1,
    },
  },
  {
    id: 162,
    name: '阀门型式',
    value: 'Valve Style',
    sort: 1,
    status: true,
    createBy: 'admin',
    updateBy: null,
    createdAt: '2024-08-02 15:36:07',
    updatedAt: '2024-08-02 15:36:07',
    remark: '',
    dictTypeId: 6,
    treeId: 6,
    tree: {
      id: 6,
      name: '状态监视器',
      value: 'Status Monitor',
      remark: null,
      parentId: 1,
    },
  },
  {
    id: 163,
    name: '执行机构类型',
    value: 'Spring Actuator Style',
    sort: 1,
    status: true,
    createBy: 'admin',
    updateBy: null,
    createdAt: '2024-08-02 15:36:07',
    updatedAt: '2024-08-02 15:36:07',
    remark: '',
    dictTypeId: 6,
    treeId: 6,
    tree: {
      id: 6,
      name: '状态监视器',
      value: 'Status Monitor',
      remark: null,
      parentId: 1,
    },
  },
  {
    id: 164,
    name: '标定日期',
    value: 'Calibration Date',
    sort: 1,
    status: true,
    createBy: 'admin',
    updateBy: null,
    createdAt: '2024-08-02 15:36:07',
    updatedAt: '2024-08-02 15:36:07',
    remark: '',
    dictTypeId: 6,
    treeId: 6,
    tree: {
      id: 6,
      name: '状态监视器',
      value: 'Status Monitor',
      remark: null,
      parentId: 1,
    },
  },
  {
    id: 165,
    name: '行程高',
    value: 'Travel High',
    sort: 1,
    status: true,
    createBy: 'admin',
    updateBy: null,
    createdAt: '2024-08-02 15:36:07',
    updatedAt: '2024-08-02 15:36:07',
    remark: '',
    dictTypeId: 6,
    treeId: 6,
    tree: {
      id: 6,
      name: '状态监视器',
      value: 'Status Monitor',
      remark: null,
      parentId: 1,
    },
  },
  {
    id: 166,
    name: '行程低',
    value: 'Travel Low',
    sort: 1,
    status: true,
    createBy: 'admin',
    updateBy: null,
    createdAt: '2024-08-02 15:36:07',
    updatedAt: '2024-08-02 15:36:07',
    remark: '',
    dictTypeId: 6,
    treeId: 6,
    tree: {
      id: 6,
      name: '状态监视器',
      value: 'Status Monitor',
      remark: null,
      parentId: 1,
    },
  },
  {
    id: 167,
    name: '行程高高',
    value: 'Travel High High',
    sort: 1,
    status: true,
    createBy: 'admin',
    updateBy: null,
    createdAt: '2024-08-02 15:36:07',
    updatedAt: '2024-08-02 15:36:07',
    remark: '',
    dictTypeId: 6,
    treeId: 6,
    tree: {
      id: 6,
      name: '状态监视器',
      value: 'Status Monitor',
      remark: null,
      parentId: 1,
    },
  },
  {
    id: 168,
    name: '行程低低',
    value: 'Travel Low Low',
    sort: 1,
    status: true,
    createBy: 'admin',
    updateBy: null,
    createdAt: '2024-08-02 15:36:07',
    updatedAt: '2024-08-02 15:36:07',
    remark: '',
    dictTypeId: 6,
    treeId: 6,
    tree: {
      id: 6,
      name: '状态监视器',
      value: 'Status Monitor',
      remark: null,
      parentId: 1,
    },
  },
  {
    id: 169,
    name: '行程偏差',
    value: 'Travel Deviation',
    sort: 1,
    status: true,
    createBy: 'admin',
    updateBy: null,
    createdAt: '2024-08-02 15:36:07',
    updatedAt: '2024-08-02 15:36:07',
    remark: '',
    dictTypeId: 6,
    treeId: 6,
    tree: {
      id: 6,
      name: '状态监视器',
      value: 'Status Monitor',
      remark: null,
      parentId: 1,
    },
  },
  {
    id: 170,
    name: '循环计数高',
    value: 'Cycle Count High',
    sort: 1,
    status: true,
    createBy: 'admin',
    updateBy: null,
    createdAt: '2024-08-02 15:36:07',
    updatedAt: '2024-08-02 15:36:07',
    remark: '',
    dictTypeId: 6,
    treeId: 6,
    tree: {
      id: 6,
      name: '状态监视器',
      value: 'Status Monitor',
      remark: null,
      parentId: 1,
    },
  },
  {
    id: 171,
    name: '行程累计高',
    value: 'Travel Accumulator High',
    sort: 1,
    status: true,
    createBy: 'admin',
    updateBy: null,
    createdAt: '2024-08-02 15:36:07',
    updatedAt: '2024-08-02 15:36:07',
    remark: '',
    dictTypeId: 6,
    treeId: 6,
    tree: {
      id: 6,
      name: '状态监视器',
      value: 'Status Monitor',
      remark: null,
      parentId: 1,
    },
  },
  {
    id: 173,
    name: '供气压力低',
    value: 'Supply Pressure',
    sort: 1,
    status: true,
    createBy: 'admin',
    updateBy: null,
    createdAt: '2024-08-02 15:36:07',
    updatedAt: '2024-08-02 15:36:07',
    remark: '',
    dictTypeId: 6,
    treeId: 6,
    tree: {
      id: 6,
      name: '状态监视器',
      value: 'Status Monitor',
      remark: null,
      parentId: 1,
    },
  },
  {
    id: 174,
    name: '组态已更改',
    value: 'Configuration Changed',
    sort: 1,
    status: true,
    createBy: 'admin',
    updateBy: null,
    createdAt: '2024-08-02 15:36:07',
    updatedAt: '2024-08-02 15:36:07',
    remark: '',
    dictTypeId: 6,
    treeId: 6,
    tree: {
      id: 6,
      name: '状态监视器',
      value: 'Status Monitor',
      remark: null,
      parentId: 1,
    },
  },
  {
    id: 175,
    name: '回路电流验证报警',
    value: 'Loop Current Validation Alert',
    sort: 1,
    status: true,
    createBy: 'admin',
    updateBy: null,
    createdAt: '2024-08-02 15:36:07',
    updatedAt: '2024-08-02 15:36:07',
    remark: '',
    dictTypeId: 6,
    treeId: 6,
    tree: {
      id: 6,
      name: '状态监视器',
      value: 'Status Monitor',
      remark: null,
      parentId: 1,
    },
  },
  {
    id: 176,
    name: '内部传感器超出限制范围',
    value: 'Internal Sensor Out of Limits',
    sort: 1,
    status: true,
    createBy: 'admin',
    updateBy: null,
    createdAt: '2024-08-02 15:36:07',
    updatedAt: '2024-08-02 15:36:07',
    remark: '',
    dictTypeId: 6,
    treeId: 6,
    tree: {
      id: 6,
      name: '状态监视器',
      value: 'Status Monitor',
      remark: null,
      parentId: 1,
    },
  },
  {
    id: 177,
    name: '变量超出范围',
    value: 'Variable Out of Range',
    sort: 1,
    status: true,
    createBy: 'admin',
    updateBy: null,
    createdAt: '2024-08-02 15:36:07',
    updatedAt: '2024-08-02 15:36:07',
    remark: '',
    dictTypeId: 6,
    treeId: 6,
    tree: {
      id: 6,
      name: '状态监视器',
      value: 'Status Monitor',
      remark: null,
      parentId: 1,
    },
  },
  {
    id: 178,
    name: '处于标定模式',
    value: 'In Calibration Mode',
    sort: 1,
    status: true,
    createBy: 'admin',
    updateBy: null,
    createdAt: '2024-08-02 15:36:07',
    updatedAt: '2024-08-02 15:36:07',
    remark: '',
    dictTypeId: 6,
    treeId: 6,
    tree: {
      id: 6,
      name: '状态监视器',
      value: 'Status Monitor',
      remark: null,
      parentId: 1,
    },
  },
  {
    id: 179,
    name: '自动校验进行中',
    value: 'Autocal in Progress',
    sort: 1,
    status: true,
    createBy: 'admin',
    updateBy: null,
    createdAt: '2024-08-02 15:36:07',
    updatedAt: '2024-08-02 15:36:07',
    remark: '',
    dictTypeId: 6,
    treeId: 6,
    tree: {
      id: 6,
      name: '状态监视器',
      value: 'Status Monitor',
      remark: null,
      parentId: 1,
    },
  },
  {
    id: 180,
    name: '诊断进行中',
    value: 'Diagnostic in Progress',
    sort: 1,
    status: true,
    createBy: 'admin',
    updateBy: null,
    createdAt: '2024-08-02 15:36:07',
    updatedAt: '2024-08-02 15:36:07',
    remark: '',
    dictTypeId: 6,
    treeId: 6,
    tree: {
      id: 6,
      name: '状态监视器',
      value: 'Status Monitor',
      remark: null,
      parentId: 1,
    },
  },
  {
    id: 181,
    name: '小回路传感器故障',
    value: 'Minor Loop Sensor Failure',
    sort: 1,
    status: true,
    createBy: 'admin',
    updateBy: null,
    createdAt: '2024-08-02 15:36:07',
    updatedAt: '2024-08-02 15:36:07',
    remark: '',
    dictTypeId: 6,
    treeId: 6,
    tree: {
      id: 6,
      name: '状态监视器',
      value: 'Status Monitor',
      remark: null,
      parentId: 1,
    },
  },
  {
    id: 182,
    name: '行程传感器故障',
    value: 'Travel Sensor Failure',
    sort: 1,
    status: true,
    createBy: 'admin',
    updateBy: null,
    createdAt: '2024-08-02 15:36:07',
    updatedAt: '2024-08-02 15:36:07',
    remark: '',
    dictTypeId: 6,
    treeId: 6,
    tree: {
      id: 6,
      name: '状态监视器',
      value: 'Status Monitor',
      remark: null,
      parentId: 1,
    },
  },
  {
    id: 183,
    name: '温度传感器故障',
    value: 'Temperature Sensor Failure',
    sort: 1,
    status: true,
    createBy: 'admin',
    updateBy: null,
    createdAt: '2024-08-02 15:36:07',
    updatedAt: '2024-08-02 15:36:07',
    remark: '',
    dictTypeId: 6,
    treeId: 6,
    tree: {
      id: 6,
      name: '状态监视器',
      value: 'Status Monitor',
      remark: null,
      parentId: 1,
    },
  },
  {
    id: 184,
    name: '压力传感器故障',
    value: 'Pressure Sensor Failure',
    sort: 1,
    status: true,
    createBy: 'admin',
    updateBy: null,
    createdAt: '2024-08-02 15:36:07',
    updatedAt: '2024-08-02 15:36:07',
    remark: '',
    dictTypeId: 6,
    treeId: 6,
    tree: {
      id: 6,
      name: '状态监视器',
      value: 'Status Monitor',
      remark: null,
      parentId: 1,
    },
  },
  {
    id: 185,
    name: '驱动电流故障',
    value: 'Drive Current Failure',
    sort: 1,
    status: true,
    createBy: 'admin',
    updateBy: null,
    createdAt: '2024-08-02 15:36:07',
    updatedAt: '2024-08-02 15:36:07',
    remark: '',
    dictTypeId: 6,
    treeId: 6,
    tree: {
      id: 6,
      name: '状态监视器',
      value: 'Status Monitor',
      remark: null,
      parentId: 1,
    },
  },
  {
    id: 186,
    name: '关键 NVM 故障',
    value: 'Critical NVM Failure',
    sort: 1,
    status: true,
    createBy: 'admin',
    updateBy: null,
    createdAt: '2024-08-02 15:36:07',
    updatedAt: '2024-08-02 15:36:07',
    remark: '',
    dictTypeId: 6,
    treeId: 6,
    tree: {
      id: 6,
      name: '状态监视器',
      value: 'Status Monitor',
      remark: null,
      parentId: 1,
    },
  },
  {
    id: 187,
    name: '闪存完整性故障',
    value: 'Flash Integrity Failure',
    sort: 1,
    status: true,
    createBy: 'admin',
    updateBy: null,
    createdAt: '2024-08-02 15:36:07',
    updatedAt: '2024-08-02 15:36:07',
    remark: '',
    dictTypeId: 6,
    treeId: 6,
    tree: {
      id: 6,
      name: '状态监视器',
      value: 'Status Monitor',
      remark: null,
      parentId: 1,
    },
  },
  {
    id: 188,
    name: '参考电压故障',
    value: 'Reference Voltage Failure',
    sort: 1,
    status: true,
    createBy: 'admin',
    updateBy: null,
    createdAt: '2024-08-02 15:36:07',
    updatedAt: '2024-08-02 15:36:07',
    remark: '',
    dictTypeId: 6,
    treeId: 6,
    tree: {
      id: 6,
      name: '状态监视器',
      value: 'Status Monitor',
      remark: null,
      parentId: 1,
    },
  },
  {
    id: 189,
    name: '报警记录非空',
    value: 'Alert Record Not Empty',
    sort: 1,
    status: true,
    createBy: 'admin',
    updateBy: null,
    createdAt: '2024-08-02 15:36:07',
    updatedAt: '2024-08-02 15:36:07',
    remark: '',
    dictTypeId: 6,
    treeId: 6,
    tree: {
      id: 6,
      name: '状态监视器',
      value: 'Status Monitor',
      remark: null,
      parentId: 1,
    },
  },
  {
    id: 190,
    name: '报警记录已满',
    value: 'Alert Record Full',
    sort: 1,
    status: true,
    createBy: 'admin',
    updateBy: null,
    createdAt: '2024-08-02 15:36:07',
    updatedAt: '2024-08-02 15:36:07',
    remark: '',
    dictTypeId: 6,
    treeId: 6,
    tree: {
      id: 6,
      name: '状态监视器',
      value: 'Status Monitor',
      remark: null,
      parentId: 1,
    },
  },
  {
    id: 191,
    name: '积分器饱和高',
    value: 'Integrator Saturated High',
    sort: 1,
    status: true,
    createBy: 'admin',
    updateBy: null,
    createdAt: '2024-08-02 15:36:07',
    updatedAt: '2024-08-02 15:36:07',
    remark: '',
    dictTypeId: 6,
    treeId: 6,
    tree: {
      id: 6,
      name: '状态监视器',
      value: 'Status Monitor',
      remark: null,
      parentId: 1,
    },
  },
  {
    id: 192,
    name: '积分器饱和低',
    value: 'Integrator Saturated Low',
    sort: 1,
    status: true,
    createBy: 'admin',
    updateBy: null,
    createdAt: '2024-08-02 15:36:07',
    updatedAt: '2024-08-02 15:36:07',
    remark: '',
    dictTypeId: 6,
    treeId: 6,
    tree: {
      id: 6,
      name: '状态监视器',
      value: 'Status Monitor',
      remark: null,
      parentId: 1,
    },
  },
  {
    id: 193,
    name: '关机激活',
    value: 'Shutdown Activated',
    sort: 1,
    status: true,
    createBy: 'admin',
    updateBy: null,
    createdAt: '2024-08-02 15:36:07',
    updatedAt: '2024-08-02 15:36:07',
    remark: '',
    dictTypeId: 6,
    treeId: 6,
    tree: {
      id: 6,
      name: '状态监视器',
      value: 'Status Monitor',
      remark: null,
      parentId: 1,
    },
  },
  {
    id: 194,
    name: '压力偏差',
    value: 'Pressure Deviation',
    sort: 1,
    status: true,
    createBy: 'admin',
    updateBy: null,
    createdAt: '2024-08-02 15:36:07',
    updatedAt: '2024-08-02 15:36:07',
    remark: '',
    dictTypeId: 6,
    treeId: 6,
    tree: {
      id: 6,
      name: '状态监视器',
      value: 'Status Monitor',
      remark: null,
      parentId: 1,
    },
  },
  {
    id: 195,
    name: '非关键 NVM 故障',
    value: 'Non-Critical NVM Failure',
    sort: 1,
    status: true,
    createBy: 'admin',
    updateBy: null,
    createdAt: '2024-08-02 15:36:07',
    updatedAt: '2024-08-02 15:36:07',
    remark: '',
    dictTypeId: 6,
    treeId: 6,
    tree: {
      id: 6,
      name: '状态监视器',
      value: 'Status Monitor',
      remark: null,
      parentId: 1,
    },
  },
  {
    id: 196,
    name: '仪表时间为大概值',
    value: 'Instrument Time is Approximate',
    sort: 1,
    status: true,
    createBy: 'admin',
    updateBy: null,
    createdAt: '2024-08-02 15:36:07',
    updatedAt: '2024-08-02 15:36:07',
    remark: '',
    dictTypeId: 6,
    treeId: 6,
    tree: {
      id: 6,
      name: '状态监视器',
      value: 'Status Monitor',
      remark: null,
      parentId: 1,
    },
  },
  {
    id: 197,
    name: '诊断数据可用',
    value: 'Diagnostic Data Available',
    sort: 1,
    status: true,
    createBy: 'admin',
    updateBy: null,
    createdAt: '2024-08-02 15:36:07',
    updatedAt: '2024-08-02 15:36:07',
    remark: '',
    dictTypeId: 6,
    treeId: 6,
    tree: {
      id: 6,
      name: '状态监视器',
      value: 'Status Monitor',
      remark: null,
      parentId: 1,
    },
  },
  {
    id: 198,
    name: '要求手动复位',
    value: 'Manual Reset Required',
    sort: 1,
    status: true,
    createBy: 'admin',
    updateBy: null,
    createdAt: '2024-08-02 15:36:07',
    updatedAt: '2024-08-02 15:36:07',
    remark: '',
    dictTypeId: 6,
    treeId: 6,
    tree: {
      id: 6,
      name: '状态监视器',
      value: 'Status Monitor',
      remark: null,
      parentId: 1,
    },
  },
  {
    id: 199,
    name: '行程高限位/截止',
    value: 'Travel Limit/Cutoff High',
    sort: 1,
    status: true,
    createBy: 'admin',
    updateBy: null,
    createdAt: '2024-08-02 15:36:07',
    updatedAt: '2024-08-02 15:36:07',
    remark: '',
    dictTypeId: 6,
    treeId: 6,
    tree: {
      id: 6,
      name: '状态监视器',
      value: 'Status Monitor',
      remark: null,
      parentId: 1,
    },
  },
  {
    id: 200,
    name: '行程低限位/截止',
    value: 'Travel Limit/Cutoff Low',
    sort: 1,
    status: true,
    createBy: 'admin',
    updateBy: null,
    createdAt: '2024-08-02 15:36:07',
    updatedAt: '2024-08-02 15:36:07',
    remark: '',
    dictTypeId: 6,
    treeId: 6,
    tree: {
      id: 6,
      name: '状态监视器',
      value: 'Status Monitor',
      remark: null,
      parentId: 1,
    },
  },
  {
    id: 201,
    name: '压力切换激活',
    value: 'Pressure Fallback Active',
    sort: 1,
    status: true,
    createBy: 'admin',
    updateBy: null,
    createdAt: '2024-08-02 15:36:07',
    updatedAt: '2024-08-02 15:36:07',
    remark: '',
    dictTypeId: 6,
    treeId: 6,
    tree: {
      id: 6,
      name: '状态监视器',
      value: 'Status Monitor',
      remark: null,
      parentId: 1,
    },
  },
  {
    id: 154,
    name: '驱动信号',
    value: 'Drive Signal',
    sort: 1,
    status: true,
    createBy: 'admin',
    updateBy: 'admin',
    createdAt: '2024-08-02 15:36:07',
    updatedAt: '2024-08-14 01:47:17',
    remark: '',
    dictTypeId: 6,
    treeId: 6,
    tree: {
      id: 6,
      name: '状态监视器',
      value: 'Status Monitor',
      parentId: 1,
    },
  },
  {
    id: 152,
    name: '行程偏差',
    value: 'Travel Deviation',
    sort: 1,
    status: true,
    createBy: 'admin',
    updateBy: 'admin',
    createdAt: '2024-08-02 15:36:07',
    updatedAt: '2024-08-14 01:47:23',
    remark: '',
    dictTypeId: 6,
    treeId: 6,
    tree: {
      id: 6,
      name: '状态监视器',
      value: 'Status Monitor',
      parentId: 1,
    },
  },

  {
    id: 202,
    name: '供气压力高',
    value: 'Supply Pressure High',
    sort: 1,
    status: true,
    createBy: 'admin',
    updateBy: null,
    createdAt: '2024-08-02 15:36:07',
    updatedAt: '2024-08-02 15:36:07',
    remark: '',
    dictTypeId: 6,
    treeId: 6,
    tree: {
      id: 6,
      name: '状态监视器',
      value: 'Status Monitor',
      remark: null,
      parentId: 1,
    },
  },
  {
    id: 203,
    name: '端口 A 过压',
    value: 'Port A Overpressurized',
    sort: 1,
    status: true,
    createBy: 'admin',
    updateBy: null,
    createdAt: '2024-08-02 15:36:07',
    updatedAt: '2024-08-02 15:36:07',
    remark: '',
    dictTypeId: 6,
    treeId: 6,
    tree: {
      id: 6,
      name: '状态监视器',
      value: 'Status Monitor',
      remark: null,
      parentId: 1,
    },
  },
  {
    id: 204,
    name: 'SOV 测试最低要求压降',
    value: 'SOV Test Min Required Pressure Drop',
    sort: 1,
    status: true,
    createBy: 'admin',
    updateBy: null,
    createdAt: '2024-08-02 15:36:07',
    updatedAt: '2024-08-02 15:36:07',
    remark: '',
    dictTypeId: 6,
    treeId: 6,
    tree: {
      id: 6,
      name: '状态监视器',
      value: 'Status Monitor',
      remark: null,
      parentId: 1,
    },
  },
  {
    id: 205,
    name: 'SOV 测试最高可允许压降',
    value: 'SOV Test Max Allowable Pressure Drop',
    sort: 1,
    status: true,
    createBy: 'admin',
    updateBy: null,
    createdAt: '2024-08-02 15:36:07',
    updatedAt: '2024-08-02 15:36:07',
    remark: '',
    dictTypeId: 6,
    treeId: 6,
    tree: {
      id: 6,
      name: '状态监视器',
      value: 'Status Monitor',
      remark: null,
      parentId: 1,
    },
  },
  {
    id: 206,
    name: '供气压力性能诊断',
    value: 'Supply Pressure Performance Diagnostic',
    sort: 1,
    status: true,
    createBy: 'admin',
    updateBy: null,
    createdAt: '2024-08-02 15:36:07',
    updatedAt: '2024-08-02 15:36:07',
    remark: '',
    dictTypeId: 6,
    treeId: 7,
    tree: {
      id: 7,
      name: '供气压力性能诊断',
      value: 'Supply Pressure Performance Diagnostic',
      remark: null,
      parentId: 1,
    },
  },
  {
    id: 207,
    name: '行程偏差性能诊断',
    value: 'Travel Deviation Performance Diagnostic',
    sort: 1,
    status: true,
    createBy: 'admin',
    updateBy: null,
    createdAt: '2024-08-02 15:36:07',
    updatedAt: '2024-08-02 15:36:07',
    remark: '',
    dictTypeId: 6,
    treeId: 8,
    tree: {
      id: 8,
      name: '行程偏差性能诊断',
      value: 'Travel Deviation Performance Diagnostic',
      remark: null,
      parentId: 1,
    },
  },
  {
    id: 208,
    name: 'I/P和放大器完整性性能诊断',
    value: 'I/P and Relay Integrity Performance Diagnostic',
    sort: 1,
    status: true,
    createBy: 'admin',
    updateBy: null,
    createdAt: '2024-08-02 15:36:07',
    updatedAt: '2024-08-02 15:36:07',
    remark: '',
    dictTypeId: 6,
    treeId: 9,
    tree: {
      id: 9,
      name: 'I/P和放大器完整性性能诊断',
      value: 'I/P and Relay Integrity Performance Diagnostic',
      remark: null,
      parentId: 1,
    },
  },
  {
    id: 209,
    name: '放大器调整性能诊断',
    value: 'Relay Adjustment Performance Diagnostic',
    sort: 1,
    status: true,
    createBy: 'admin',
    updateBy: null,
    createdAt: '2024-08-02 15:36:07',
    updatedAt: '2024-08-02 15:36:07',
    remark: '',
    dictTypeId: 6,
    treeId: 10,
    tree: {
      id: 10,
      name: '放大器调整性能诊断',
      value: 'Relay Adjustment Performance Diagnostic',
      remark: null,
      parentId: 1,
    },
  },
  {
    id: 210,
    name: '空气质量流量性能诊断',
    value: 'Air Mass Flow Performance Diagnostic',
    sort: 1,
    status: true,
    createBy: 'admin',
    updateBy: null,
    createdAt: '2024-08-02 15:36:07',
    updatedAt: '2024-08-02 15:36:07',
    remark: '',
    dictTypeId: 6,
    treeId: 11,
    tree: {
      id: 11,
      name: '空气质量流量性能诊断',
      value: 'Air Mass Flow Performance Diagnostic',
      remark: null,
      parentId: 1,
    },
  },
  {
    id: 211,
    name: '阀门摩擦力性能诊断',
    value: 'Valve Friction Performance Diagnostic',
    sort: 1,
    status: true,
    createBy: 'admin',
    updateBy: null,
    createdAt: '2024-08-02 15:36:07',
    updatedAt: '2024-08-02 15:36:07',
    remark: '',
    dictTypeId: 6,
    treeId: 12,
    tree: {
      id: 12,
      name: '阀门摩擦力性能诊断',
      value: 'Valve Friction Performance Diagnostic',
      remark: null,
      parentId: 1,
    },
  },
  {
    id: 212,
    name: '反馈连接方式',
    value: 'Feedback Connection',
    sort: 1,
    status: true,
    createBy: 'admin',
    updateBy: null,
    createdAt: '2024-08-02 15:36:07',
    updatedAt: '2024-08-02 15:36:07',
    remark: '',
    dictTypeId: 6,
    treeId: 17,
    tree: {
      id: 17,
      name: '阶跃响应',
      value: 'Step Response',
      remark: null,
      parentId: 1,
    },
  },
  {
    id: 213,
    name: '零功率状态',
    value: 'Zero Power Condition',
    sort: 1,
    status: true,
    createBy: 'admin',
    updateBy: null,
    createdAt: '2024-08-02 15:36:07',
    updatedAt: '2024-08-02 15:36:07',
    remark: '',
    dictTypeId: 6,
    treeId: 17,
    tree: {
      id: 17,
      name: '阶跃响应',
      value: 'Step Response',
      remark: null,
      parentId: 1,
    },
  },
  {
    id: 214,
    name: '行程整定参数',
    value: 'Travel Tuning Set',
    sort: 1,
    status: true,
    createBy: 'admin',
    updateBy: null,
    createdAt: '2024-08-02 15:36:07',
    updatedAt: '2024-08-02 15:36:07',
    remark: '',
    dictTypeId: 6,
    treeId: 17,
    tree: {
      id: 17,
      name: '阶跃响应',
      value: 'Step Response',
      remark: null,
      parentId: 1,
    },
  },
  {
    id: 215,
    name: '比例',
    value: 'Proportional',
    sort: 1,
    status: true,
    createBy: 'admin',
    updateBy: null,
    createdAt: '2024-08-02 15:36:07',
    updatedAt: '2024-08-02 15:36:07',
    remark: '',
    dictTypeId: 6,
    treeId: 17,
    tree: {
      id: 17,
      name: '阶跃响应',
      value: 'Step Response',
      remark: null,
      parentId: 1,
    },
  },
  {
    id: 216,
    name: '速度：',
    value: 'Velocity',
    sort: 1,
    status: true,
    createBy: 'admin',
    updateBy: null,
    createdAt: '2024-08-02 15:36:07',
    updatedAt: '2024-08-02 15:36:07',
    remark: '',
    dictTypeId: 6,
    treeId: 17,
    tree: {
      id: 17,
      name: '阶跃响应',
      value: 'Step Response',
      remark: null,
      parentId: 1,
    },
  },
  {
    id: 217,
    name: 'MLF',
    value: 'MLF',
    sort: 1,
    status: true,
    createBy: 'admin',
    updateBy: null,
    createdAt: '2024-08-02 15:36:07',
    updatedAt: '2024-08-02 15:36:07',
    remark: '',
    dictTypeId: 6,
    treeId: 17,
    tree: {
      id: 17,
      name: '阶跃响应',
      value: 'Step Response',
      remark: null,
      parentId: 1,
    },
  },
  {
    id: 218,
    name: '1',
    value: '1',
    sort: 1,
    status: true,
    createBy: 'admin',
    updateBy: null,
    createdAt: '2024-08-02 15:36:07',
    updatedAt: '2024-08-02 15:36:07',
    remark: '',
    dictTypeId: 6,
    treeId: 18,
    tree: {
      id: 18,
      name: '阶跃响应-已分析的数据',
      value: 'Step Response-Analyzed Data',
      remark: null,
      parentId: 1,
    },
  },
  {
    id: 219,
    name: '2',
    value: '2',
    sort: 1,
    status: true,
    createBy: 'admin',
    updateBy: null,
    createdAt: '2024-08-02 15:36:07',
    updatedAt: '2024-08-02 15:36:07',
    remark: '',
    dictTypeId: 6,
    treeId: 18,
    tree: {
      id: 18,
      name: '阶跃响应-已分析的数据',
      value: 'Step Response-Analyzed Data',
      remark: null,
      parentId: 1,
    },
  },
  {
    id: 220,
    name: '3',
    value: '3',
    sort: 1,
    status: true,
    createBy: 'admin',
    updateBy: null,
    createdAt: '2024-08-02 15:36:07',
    updatedAt: '2024-08-02 15:36:07',
    remark: '',
    dictTypeId: 6,
    treeId: 18,
    tree: {
      id: 18,
      name: '阶跃响应-已分析的数据',
      value: 'Step Response-Analyzed Data',
      remark: null,
      parentId: 1,
    },
  },
  {
    id: 221,
    name: '4',
    value: '4',
    sort: 1,
    status: true,
    createBy: 'admin',
    updateBy: null,
    createdAt: '2024-08-02 15:36:07',
    updatedAt: '2024-08-02 15:36:07',
    remark: '',
    dictTypeId: 6,
    treeId: 18,
    tree: {
      id: 18,
      name: '阶跃响应-已分析的数据',
      value: 'Step Response-Analyzed Data',
      remark: null,
      parentId: 1,
    },
  },
  {
    id: 222,
    name: '5',
    value: '5',
    sort: 1,
    status: true,
    createBy: 'admin',
    updateBy: null,
    createdAt: '2024-08-02 15:36:07',
    updatedAt: '2024-08-02 15:36:07',
    remark: '',
    dictTypeId: 6,
    treeId: 18,
    tree: {
      id: 18,
      name: '阶跃响应-已分析的数据',
      value: 'Step Response-Analyzed Data',
      remark: null,
      parentId: 1,
    },
  },
  {
    id: 223,
    name: '6',
    value: '6',
    sort: 1,
    status: true,
    createBy: 'admin',
    updateBy: null,
    createdAt: '2024-08-02 15:36:07',
    updatedAt: '2024-08-02 15:36:07',
    remark: '',
    dictTypeId: 6,
    treeId: 18,
    tree: {
      id: 18,
      name: '阶跃响应-已分析的数据',
      value: 'Step Response-Analyzed Data',
      remark: null,
      parentId: 1,
    },
  },
  {
    id: 224,
    name: '7',
    value: '7',
    sort: 1,
    status: true,
    createBy: 'admin',
    updateBy: null,
    createdAt: '2024-08-02 15:36:07',
    updatedAt: '2024-08-02 15:36:07',
    remark: '',
    dictTypeId: 6,
    treeId: 18,
    tree: {
      id: 18,
      name: '阶跃响应-已分析的数据',
      value: 'Step Response-Analyzed Data',
      remark: null,
      parentId: 1,
    },
  },
  {
    id: 225,
    name: '8',
    value: '8',
    sort: 1,
    status: true,
    createBy: 'admin',
    updateBy: null,
    createdAt: '2024-08-02 15:36:07',
    updatedAt: '2024-08-02 15:36:07',
    remark: '',
    dictTypeId: 6,
    treeId: 18,
    tree: {
      id: 18,
      name: '阶跃响应-已分析的数据',
      value: 'Step Response-Analyzed Data',
      remark: null,
      parentId: 1,
    },
  },
  {
    id: 226,
    name: '9',
    value: '9',
    sort: 1,
    status: true,
    createBy: 'admin',
    updateBy: null,
    createdAt: '2024-08-02 15:36:07',
    updatedAt: '2024-08-02 15:36:07',
    remark: '',
    dictTypeId: 6,
    treeId: 18,
    tree: {
      id: 18,
      name: '阶跃响应-已分析的数据',
      value: 'Step Response-Analyzed Data',
      remark: null,
      parentId: 1,
    },
  },
  {
    id: 227,
    name: '10',
    value: '10',
    sort: 1,
    status: true,
    createBy: 'admin',
    updateBy: null,
    createdAt: '2024-08-02 15:36:07',
    updatedAt: '2024-08-02 15:36:07',
    remark: '',
    dictTypeId: 6,
    treeId: 18,
    tree: {
      id: 18,
      name: '阶跃响应-已分析的数据',
      value: 'Step Response-Analyzed Data',
      remark: null,
      parentId: 1,
    },
  },
  {
    id: 228,
    name: '11',
    value: '11',
    sort: 1,
    status: true,
    createBy: 'admin',
    updateBy: null,
    createdAt: '2024-08-02 15:36:07',
    updatedAt: '2024-08-02 15:36:07',
    remark: '',
    dictTypeId: 6,
    treeId: 18,
    tree: {
      id: 18,
      name: '阶跃响应-已分析的数据',
      value: 'Step Response-Analyzed Data',
      remark: null,
      parentId: 1,
    },
  },
  {
    id: 229,
    name: '12',
    value: '12',
    sort: 1,
    status: true,
    createBy: 'admin',
    updateBy: null,
    createdAt: '2024-08-02 15:36:07',
    updatedAt: '2024-08-02 15:36:07',
    remark: '',
    dictTypeId: 6,
    treeId: 18,
    tree: {
      id: 18,
      name: '阶跃响应-已分析的数据',
      value: 'Step Response-Analyzed Data',
      remark: null,
      parentId: 1,
    },
  },
  {
    id: 230,
    name: '扫描时间',
    value: 'Scan Time',
    sort: 1,
    status: true,
    createBy: 'admin',
    updateBy: null,
    createdAt: '2024-08-02 15:36:07',
    updatedAt: '2024-08-02 15:36:07',
    remark: '',
    dictTypeId: 6,
    treeId: 13,
    tree: {
      id: 13,
      name: '完全扫描',
      value: 'Total Scan',
      remark: null,
      parentId: 1,
    },
  },
  {
    id: 231,
    name: '平均动态误差',
    value: 'Avg. Dynamic Error',
    sort: 1,
    status: true,
    createBy: 'admin',
    updateBy: null,
    createdAt: '2024-08-02 15:36:07',
    updatedAt: '2024-08-02 15:36:07',
    remark: '',
    dictTypeId: 6,
    treeId: 13,
    tree: {
      id: 13,
      name: '完全扫描',
      value: 'Total Scan',
      remark: null,
      parentId: 1,
    },
  },
  {
    id: 232,
    name: '动态线性度（独立）',
    value: 'Dyn. Linearity (Ind.)',
    sort: 1,
    status: true,
    createBy: 'admin',
    updateBy: null,
    createdAt: '2024-08-02 15:36:07',
    updatedAt: '2024-08-02 15:36:07',
    remark: '',
    dictTypeId: 6,
    treeId: 13,
    tree: {
      id: 13,
      name: '完全扫描',
      value: 'Total Scan',
      remark: null,
      parentId: 1,
    },
  },
  {
    id: 233,
    name: '平均扭矩',
    value: 'Average Torque',
    sort: 1,
    status: true,
    createBy: 'admin',
    updateBy: null,
    createdAt: '2024-08-02 15:36:07',
    updatedAt: '2024-08-02 15:36:07',
    remark: '',
    dictTypeId: 6,
    treeId: 13,
    tree: {
      id: 13,
      name: '完全扫描',
      value: 'Total Scan',
      remark: null,
      parentId: 1,
    },
  },
  {
    id: 234,
    name: '弹簧预紧力',
    value: 'Bench Set',
    sort: 1,
    status: true,
    createBy: 'admin',
    updateBy: null,
    createdAt: '2024-08-02 15:36:07',
    updatedAt: '2024-08-02 15:36:07',
    remark: '',
    dictTypeId: 6,
    treeId: 13,
    tree: {
      id: 13,
      name: '完全扫描',
      value: 'Total Scan',
      remark: null,
      parentId: 1,
    },
  },
  {
    id: 235,
    name: '额定行程',
    value: 'Rated Travel',
    sort: 1,
    status: true,
    createBy: 'admin',
    updateBy: null,
    createdAt: '2024-08-02 15:36:07',
    updatedAt: '2024-08-02 15:36:07',
    remark: '',
    dictTypeId: 6,
    treeId: 16,
    tree: {
      id: 16,
      name: '完全扫描-规格表',
      value: 'Total Scan-Spec Sheet',
      remark: null,
      parentId: 1,
    },
  },
  {
    id: 236,
    name: '实际行程：',
    value: 'Actual Travel',
    sort: 1,
    status: true,
    createBy: 'admin',
    updateBy: null,
    createdAt: '2024-08-02 15:36:07',
    updatedAt: '2024-08-02 15:36:07',
    remark: '',
    dictTypeId: 6,
    treeId: 16,
    tree: {
      id: 16,
      name: '完全扫描-规格表',
      value: 'Total Scan-Spec Sheet',
      remark: null,
      parentId: 1,
    },
  },
  {
    id: 237,
    name: '下方弹簧预紧力',
    value: 'Lower Bench Set',
    sort: 1,
    status: true,
    createBy: 'admin',
    updateBy: null,
    createdAt: '2024-08-02 15:36:07',
    updatedAt: '2024-08-02 15:36:07',
    remark: '',
    dictTypeId: 6,
    treeId: 16,
    tree: {
      id: 16,
      name: '完全扫描-规格表',
      value: 'Total Scan-Spec Sheet',
      remark: null,
      parentId: 1,
    },
  },
  {
    id: 238,
    name: '上方弹簧预紧力',
    value: 'Upper Bench Set',
    sort: 1,
    status: true,
    createBy: 'admin',
    updateBy: null,
    createdAt: '2024-08-02 15:36:07',
    updatedAt: '2024-08-02 15:36:07',
    remark: '',
    dictTypeId: 6,
    treeId: 16,
    tree: {
      id: 16,
      name: '完全扫描-规格表',
      value: 'Total Scan-Spec Sheet',
      remark: null,
      parentId: 1,
    },
  },
  {
    id: 286,
    name: '循环计数',
    value: 'Cycle Count',
    sort: 1,
    status: true,
    createBy: 'admin',
    updateBy: null,
    createdAt: '2024-08-06 18:58:22',
    updatedAt: '2024-08-06 18:58:22',
    remark: '',
    dictTypeId: 6,
    treeId: 6,
    tree: {
      id: 6,
      name: '状态监视器',
      value: 'Status Monitor',
      remark: null,
      parentId: 1,
    },
  },
  {
    id: 287,
    name: '平均扭矩',
    value: 'Avg. Torque',
    sort: 1,
    status: true,
    createBy: 'admin',
    updateBy: null,
    createdAt: '2024-08-14 01:14:24',
    updatedAt: '2024-08-14 01:14:24',
    remark: '',
    dictTypeId: 6,
    treeId: 12,
    tree: {
      id: 12,
      name: '阀门摩擦力性能诊断',
      value: 'Valve Friction Performance Diagnostic',
      remark: null,
      parentId: 1,
    },
  },
  {
    id: 288,
    name: '平均死区',
    value: 'Avg. Dead Band',
    sort: 1,
    status: true,
    createBy: 'admin',
    updateBy: null,
    createdAt: '2024-08-14 01:14:47',
    updatedAt: '2024-08-14 01:14:47',
    remark: '',
    dictTypeId: 6,
    treeId: 12,
    tree: {
      id: 12,
      name: '阀门摩擦力性能诊断',
      value: 'Valve Friction Performance Diagnostic',
      remark: null,
      parentId: 1,
    },
  },
  {
    id: 289,
    name: '测试状态阀座负载',
    value: 'Seat Load As Tested',
    sort: 1,
    status: true,
    createBy: 'admin',
    updateBy: null,
    createdAt: '2024-08-14 01:15:21',
    updatedAt: '2024-08-14 01:15:21',
    remark: '',
    dictTypeId: 6,
    treeId: 13,
    tree: {
      id: 13,
      name: '完全扫描',
      value: 'Total Scan',
      remark: null,
      parentId: 1,
    },
  },
  {
    id: 290,
    name: '投用状态阀座负载',
    value: 'Service Seat Load',
    sort: 1,
    status: true,
    createBy: 'admin',
    updateBy: null,
    createdAt: '2024-08-14 01:15:44',
    updatedAt: '2024-08-14 01:15:44',
    remark: '',
    dictTypeId: 6,
    treeId: 13,
    tree: {
      id: 13,
      name: '完全扫描',
      value: 'Total Scan',
      remark: null,
      parentId: 1,
    },
  },
  {
    id: 291,
    name: '所需阀座负载',
    value: 'Required Seat Load',
    sort: 1,
    status: true,
    createBy: 'admin',
    updateBy: null,
    createdAt: '2024-08-14 01:16:09',
    updatedAt: '2024-08-14 01:16:09',
    remark: '',
    dictTypeId: 6,
    treeId: 13,
    tree: {
      id: 13,
      name: '完全扫描',
      value: 'Total Scan',
      remark: null,
      parentId: 1,
    },
  },
  {
    id: 292,
    name: '预期总摩擦力',
    value: 'Expected Total Friction',
    sort: 1,
    status: true,
    createBy: 'admin',
    updateBy: null,
    createdAt: '2024-08-14 01:16:45',
    updatedAt: '2024-08-14 01:16:45',
    remark: '',
    dictTypeId: 6,
    treeId: 13,
    tree: {
      id: 13,
      name: '完全扫描',
      value: 'Total Scan',
      remark: null,
      parentId: 1,
    },
  },
  {
    id: 293,
    name: '增压器',
    value: 'Volume Booster',
    sort: 1,
    status: true,
    createBy: 'admin',
    updateBy: null,
    createdAt: '2024-08-14 01:49:36',
    updatedAt: '2024-08-14 01:49:36',
    remark: '',
    dictTypeId: 6,
    treeId: 16,
    tree: {
      id: 16,
      name: '完全扫描-规格表',
      value: 'Total Scan-Spec Sheet',
      remark: null,
      parentId: 1,
    },
  },
];
